server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/app
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "change_me"